name: "Test Deploy Terraform stacks"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/terraform-plan-apply.yml
      - .github/workflows/_test-terraform-plan-apply.yml
      - .github/workflows/terraform-core.yml

jobs:
  deploy_tf_stacks_regression_test:
    name: Test using devops-terraform-example-project@main
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
