name: "[Setup] Initialise and perform Terraform actions"
on:
  workflow_call:
    inputs:
      environment_name:
        required: false
        default: dev
        type: string
      aws_region:
        required: false
        default: eu-west-2
        type: string
      execute_terraform_plan:
        required: false
        type: boolean
        default: false
        description: "Whether or not to apply the Terraform code. Set to false for a plan only."
      terraform_action:
        required: false
        type: string
        default: "apply"
        description: "Which Terraform action to run. 'apply' or 'destroy'"
      stack_config:
        description: "JSON containing the Terraform stack configuration and dependencies"
        required: true
        type: string
      max_parallel:
        required: false
        description: "The maximum number of jobs to run at the same time. This should normally be 1 to avoid race conditions."
        type: number
        default: 1
      terraform_arg_refresh:
        required: false
        description: "Whether or not to refresh Terraform state when running Terraform commands. Should be 'true' (string, not boolean) for scheduled drift detection workflows."
        type: string
        default: "false"
      repo:
        required: false
        type: string
        default: ${{ github.repository }}
        description: "Specify the org/repo of the repo containing Terraform code. Normally left blank to clone calling repo."
      ref:
        required: false
        type: string
        default: ${{ github.ref }}
        description: "Specify the branch of the Terraform code. Normally left blank to use calling ref."
      upload_plan:
        required: false
        type: boolean
        default: true
        description: "Create an artifact containing the resulting Terraform plan."
      python_version:
        required: false
        type: string
        default: "3.12"
        description: "The version of python required when building packages via Terraform"
      artefact_path:
        required: false
        type: string
        default: "nonexistentfile.txt"
        description: "If there are artefacts created from data sources, specify the path from the TF stack dir here so they are uploaded before applying"
      other_variables:
        required: false
        type: string
        default: "{}"
        description: "JSON map of additional Terraform variables to export as TF_VAR_* environment variables"
    secrets:
      AWS_ROLE_NAME:
        required: false
        description: "The name of the role to assume when Terraform interacts with the AWS API."
      AWS_ACCOUNT_ID:
        required: false
        description: "The AWS account ID where Terraform will create resources. This account must contain the role specified in AWS_ROLE_NAME."
      AWS_ACCESS_KEY_ID:
        required: false
        description: "AWS credentials used by Terraform to interact with AWS API. Not required if using OIDC."
      AWS_SECRET_ACCESS_KEY:
        required: false
        description: "AWS credentials used by Terraform to interact with AWS API. Not required if using OIDC."
      AZURE_SUBSCRIPTION_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_RESOURCE_GROUP_NAME:
        required: false
      GH_TOKEN:
        required: false
        description: "Github Token used by Terraform to create and manage resources in Github"
      TF_MODULES_SSH_DEPLOY_KEY:
        required: false
        description: "The SSH key used to clone Terraform modules downloaded as part of the Terraform init"
      REPO_SSH_DEPLOY_KEY:
        required: false
        description: "The SSH key used to checkout private remote repos"
      SSH_DEPLOY_KEY:
        required: false
        description: "Deprecated: Use either TF_MODULES_SSH_DEPLOY_KEY or REPO_SSH_DEPLOY_KEY instead."
      TF_PLAN_ENCRYPTION_PASSPHRASE:
        required: true
        description: "The passphrase used to encrypt Terraform Plans before uploading them as Github Artifacts"

env:
  TERRAFORM_ARGS: "-refresh=${{ inputs.terraform_arg_refresh }} -no-color -lock-timeout=5m -input=false"
  TERRAFORM_COMMAND: "terraform"

jobs:
  terraform:
    name: "Initialise and run Terraform for ${{ matrix.stack.directory }}"
    runs-on: "${{ matrix.stack.runner_label }}"
    environment: ${{ inputs.environment_name }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        stack: "${{ fromJSON(inputs.stack_config) }}"
      max-parallel: ${{ inputs.max_parallel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          ssh-key: ${{ secrets.REPO_SSH_DEPLOY_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Checkout workflow utilities
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.workflow_sha }}
          path: __workflow
          fetch-depth: 1
          sparse-checkout: |
            .github

      - name: Register workflow scripts path
        run: echo "WORKFLOW_SCRIPTS_DIR=$GITHUB_WORKSPACE/__workflow/.github/scripts" >> $GITHUB_ENV

      - name: Export variables
        env:
          STACK_DIRECTORY: ${{ matrix.stack.directory }}
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/export-state-name.sh

      - name: Export user provided Terraform variables
        if: ${{ inputs.other_variables != '' }}
        env:
          RAW_TERRAFORM_VARS: ${{ inputs.other_variables }}
        run: python3 $WORKFLOW_SCRIPTS_DIR/terraform-core/export-user-variables.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"
          AWS_ROLE_NAME: "${{ secrets.AWS_ROLE_NAME }}"
        if: ${{ env.AWS_ROLE_NAME != '' && env.AWS_ACCOUNT_ID != '' }}
        with:
          aws-region: "${{ inputs.aws_region }}"
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}"
          aws-access-key-id: "${{ env.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: Configure Azure Credentials
        uses: azure/login@v2
        env:
          AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
          AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        if: >-
          ${{ env.AZURE_CLIENT_ID != '' && env.AZURE_TENANT_ID != '' &&
          env.AZURE_SUBSCRIPTION_ID != '' }}
        with:
          client-id: "${{ env.AZURE_CLIENT_ID }}"
          tenant-id: "${{ env.AZURE_TENANT_ID }}"
          subscription-id: "${{ env.AZURE_SUBSCRIPTION_ID }}"

      - name: Copy required files from root directory
        env:
          DIRECTORY: "${{ matrix.stack.directory }}"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/copy-required-files.sh

      - name: Decide which Terraform version to use based on constraints
        uses: ukhsa-collaboration/devops-github-actions/.github/actions/parse-terraform-version@v0.9.1
        id: terraform_version
        with:
          tf_file: "${{ matrix.stack.directory }}/terraform.tf"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ steps.terraform_version.outputs.tf_version }}"
          terraform_wrapper: false

      - name: Determine Backend Type
        working-directory: "${{ matrix.stack.directory }}"
        id: backend
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/determine-backend-type.sh

      - name: Add SSH deploy key to ssh-agent
        env:
          SSH_DEPLOY_KEY: ${{ secrets.TF_MODULES_SSH_DEPLOY_KEY != '' && secrets.TF_MODULES_SSH_DEPLOY_KEY || secrets.SSH_DEPLOY_KEY }}
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/add-ssh-deploy-key.sh

      - name: Configure Terraform plugin cache
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/configure-plugin-cache.sh

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
  
      - name: Terraform Init with AWS S3 Backend
        working-directory: "${{ matrix.stack.directory }}"
        if: ${{ steps.backend.outputs.backend_type == 's3' }}
        env:
          AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"
          AWS_REGION: "${{ inputs.aws_region }}"
          ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
          DIRECTORY: "${{ matrix.stack.directory }}"
          TF_VERSION: "${{ steps.terraform_version.outputs.tf_version }}"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/terraform-init-s3.sh

      - name: Terraform Init with Azure Backend
        if: ${{ steps.backend.outputs.backend_type == 'azurerm' }}
        working-directory: "${{ matrix.stack.directory }}"
        env:
          ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
          DIRECTORY: "${{ matrix.stack.directory }}"
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
          AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          AZURE_RESOURCE_GROUP_NAME: "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/terraform-init-azure.sh

      - name: Find Terraform variables
        id: variables
        shell: bash
        env:
          DIRECTORY: "${{ matrix.stack.directory }}"
          ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/find-terraform-variables.sh


      - name: Terraform Plan
        id: tf_plan
        working-directory: "${{ matrix.stack.directory }}"
        shell: bash
        env:
          ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
          TERRAFORM_VARIABLES: "${{ steps.variables.outputs.tf_vars }}"
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TERRAFORM_ACTION: ${{ inputs.terraform_action }}
          SKIP_DESTROY: "${{ matrix.stack.skip_when_destroying }}"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/terraform-plan.sh

      - name: Update stack matrix
        working-directory: "${{ matrix.stack.directory }}"
        env:
          STACK_DIRECTORY: ${{ matrix.stack.directory }}
          RUNNER_LABEL_JSON: '${{ toJSON(matrix.stack.runner_label) }}'
          PLANNED_CHANGES: ${{ steps.tf_plan.outputs.planned_changes }}
          STACK_ORDER: ${{ matrix.stack.order }}
          SKIP_WHEN_DESTROYING: ${{ matrix.stack.skip_when_destroying }}
        run: python3 $WORKFLOW_SCRIPTS_DIR/terraform-core/update-stack-matrix.py
  
      - name: Terraform Apply
        # We don't want to apply if there are no planned changes OR if we're destroying and
        # this stack's dependencies.json file has `skip_when_destroying` set to true.
        if: >-
            ${{ inputs.execute_terraform_plan == true &&
            steps.tf_plan.outputs.planned_changes == 'true' && (
            inputs.terraform_action != 'destroy' || matrix.stack.skip_when_destroying ==
            false ) }}
        working-directory: "${{ matrix.stack.directory }}"
        env:
          ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
          TERRAFORM_VARIABLES: "${{ steps.variables.outputs.tf_vars }}"
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/terraform-apply.sh

      - name: Encrypt Terraform plan
        id: encrypt_plan
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.TF_PLAN_ENCRYPTION_PASSPHRASE }}
        working-directory: "${{ matrix.stack.directory }}"
        if: ${{ inputs.upload_plan && steps.tf_plan.conclusion != 'skipped' && steps.tf_plan.outputs.planned_changes == 'true' }}
        run: $WORKFLOW_SCRIPTS_DIR/terraform-core/encrypt-terraform-plan.sh

      - name: Upload Job Artefacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_plan }}
        with:
          name: "${{ env.state_name }}-${{ inputs.environment_name }}-artefacts"
          path: |
            ${{ matrix.stack.directory }}/tfplan.gpg
            ${{ matrix.stack.directory }}/tfplan.json.gpg
            ${{ matrix.stack.directory }}/updated_matrix.json
            ${{ matrix.stack.directory }}/${{ inputs.artefact_path }}
          if-no-files-found: warn
          compression-level: 1
          retention-days: 1
