name: "[CI] Plan Terraform Stacks"
on:
  workflow_call:
    inputs:
      environment_name:
        required: false
        default: dev
        type: string
      aws_region:
        required: false
        default: eu-west-2
        type: string
      repo:
        required: false
        type: string
        default: ${{ github.repository }}
      ref:
        required: false
        type: string
        default: ${{ github.ref }}

    secrets:
      AWS_ROLE_NAME:
        required: false
      AWS_ACCOUNT_ID:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      TF_MODULES_SSH_DEPLOY_KEY:
        required: false
      REPO_SSH_DEPLOY_KEY:
        required: false
      TF_PLAN_ENCRYPTION_PASSPHRASE:
        required: true
        description: "The passphrase used to encrypt Terraform Plans before uploading them as Github Artifacts"
  

jobs:
  define_matrix:
    name: Define directory matrix for build
    runs-on: ubuntu-latest
    outputs:
      stack_config: "${{ steps.stack_config.outputs.json_directory_list }}"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          ssh-key: ${{ secrets.REPO_SSH_DEPLOY_KEY }}
      - name: Determine order to run Terraform stacks
        uses: >-
          ukhsa-collaboration/devops-github-actions/.github/actions/terraform-dependency-sort@dea5f8f73cde1ca4bbd2a29b6b59bd8264af27f8
        id: stack_config

  check:
    name: Lint and SAST Scan Terraform code
    uses: ./.github/workflows/terraform-code-check.yml
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
    secrets:
      REPO_SSH_DEPLOY_KEY: ${{ secrets.REPO_SSH_DEPLOY_KEY }}

  filter_matrix:
    name: Filter matrix for only planned changes
    needs:
      - define_matrix
    runs-on: ubuntu-latest
    outputs:
      filtered_matrix: ${{ steps.filter_matrix.outputs.filtered_matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          ssh-key: ${{ secrets.REPO_SSH_DEPLOY_KEY }}
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.workflow_sha }}
          path: __workflow
          fetch-depth: 1
          sparse-checkout: |
            .github
      - name: Register workflow scripts path
        run: echo "WORKFLOW_SCRIPTS_DIR=$GITHUB_WORKSPACE/__workflow/.github/scripts" >> $GITHUB_ENV

      - name: Filter Stacks
        env:
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
          STACK_CONFIG_JSON: '${{ needs.define_matrix.outputs.stack_config }}'
        id: filter_matrix
        run: $WORKFLOW_SCRIPTS_DIR/common/filter-stacks.sh

  plan:
    name: Plan Terraform
    uses: ./.github/workflows/terraform-core.yml
    needs:
      - filter_matrix
    with:
      environment_name: ${{ inputs.environment_name }}
      aws_region: ${{ inputs.aws_region }}
      repo: ${{ inputs.repo }}
      ref:  ${{ inputs.ref }}
      stack_config: "${{ needs.filter_matrix.outputs.filtered_matrix }}"
      terraform_action: "apply"
      execute_terraform_plan: false
      upload_plan: true
    secrets: inherit

  comment:
    name: Comment plan on Pull Request
    if: github.event_name == 'pull_request'
    needs:
      - plan
      - filter_matrix
    runs-on: "${{ matrix.stack.runner_label }}"
    strategy:
      matrix:
        stack: "${{ fromJSON(needs.filter_matrix.outputs.filtered_matrix) }}"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          ssh-key: ${{ secrets.REPO_SSH_DEPLOY_KEY }}
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.workflow_sha }}
          path: __workflow
          fetch-depth: 1
          sparse-checkout: |
            .github
      - name: Register workflow scripts path
        run: echo "WORKFLOW_SCRIPTS_DIR=$GITHUB_WORKSPACE/__workflow/.github/scripts" >> $GITHUB_ENV

      - name: Export variables
        id: variables
        env:
          STACK_DIRECTORY: ${{ matrix.stack.directory }}
        run: $WORKFLOW_SCRIPTS_DIR/terraform-plan/export-state-name-output.sh

      - uses: actions/download-artifact@v4
        id: download
        with:
          name: "${{ steps.variables.outputs.state_name }}-${{ inputs.environment_name }}-artefacts"
          path: "${{ inputs.environment_name }}/${{ steps.variables.outputs.state_name }}"

      - name: Check if there are any changes
        working-directory: ${{ steps.download.outputs.download-path }}
        id: changes
        run: $WORKFLOW_SCRIPTS_DIR/terraform-plan/check-planned-changes.sh
  
      - name: Decrypt Terraform Plan
        working-directory: ${{ steps.download.outputs.download-path }}
        if: steps.changes.outputs.planned_changes == 'true'
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.TF_PLAN_ENCRYPTION_PASSPHRASE }}
        run: $WORKFLOW_SCRIPTS_DIR/terraform-plan/decrypt-plan.sh
  
      - name: Comment plan on PR
        uses: actions/github-script@v7
        if: steps.changes.outputs.planned_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const script = require('${{ env.WORKFLOW_SCRIPTS_DIR }}/terraform-core/encrypt-terraform-plan.sh')
            console.log(script({github, context}))
